/// analysis.components.token defines the Token struct that is generated by the lexer
module analysis.components.token;

import bnf.symbols : Terminal;

struct Token
{
  Terminal kind;
  string lexeme;
  size_t startPosition;
}
